//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Komis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carreg
    {
        public int id { get; set; }
        public string VIN { get; set; }
        public string nr_tablicy { get; set; }
        public string marka { get; set; }
        public int rocznik { get; set; }
        public int przebieg { get; set; }
        public string kolor { get; set; }
        public string dostepnosc { get; set; }
    }
}
