//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Komis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sprzedaz
    {
        public int id { get; set; }
        public string carid { get; set; }
        public int custid { get; set; }
        public decimal cena { get; set; }
        public System.DateTime data_sprzedazy { get; set; }
    }
}
